idle_bg = "#161616"
idle_fg = "#dde1e6"
info_bg = "#78a9ff"
info_fg = "#161616"
good_bg = "#78a9ff"
good_fg = "#161616"
warning_bg = "#ff7eb6"
warning_fg = "#dde1e6"
critical_bg = "#ee5396"
critical_fg = "#dde1e6"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
