# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# Project:    Nord Alacritty
# Version:    0.1.0
# Repository: https://github.com/arcticicestudio/nord-alacritty
# License:    MIT
# References:
#   https://github.com/alacritty/alacritty
env:
  WINIT_X11_SCALE_FACTOR: "1.0"

font:
  normal:
    family: Source Code Pro
    style: Regular
    bold:
    family: Source Code Pro
    style: Bold
  italic:
    family: Source Code Pro
    style: Italic
  bold_italic:
    family: Source Code Pro
    style: Bold Italic
  size: 11

colors:
  primary:
    background: '#161616'
    foreground: '#ffffff'
  cursor:
    cursor: '#dde1e6'
  normal:
    black: '#161616'
    red: '#33b1ff'
    green: '#ff7eb6'
    yellow: '#42be65'
    blue: '#08bdba'
    magenta: '#82cfff'
    cyan: '#78a9ff'
    white: '#e5e9f0'
  bright:
    black: '#525252'
    red: '#33b1ff'
    green: '#ff7eb6'
    yellow: '#42be65'
    blue: '#08bdba'
    magenta: '#82cfff'
    cyan: '#78a9ff'
    white: '#ffffff'

