# Author: Kevin Fritz <kevinfritz210@gmail.com>

"ui.background" = { bg = "base00" }
"ui.virtual.whitespace" = "base03"
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"comment" = { fg = "base03", modifiers = ["italic"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.text" = "base05"
"operator" = "base0B"
"ui.text.focus" = "base05"
"variable" = "base04"
"constant.numeric" = "base09"
"constant" = "base09"
"attribute" = "base09"
"type" = "base07"
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"string"  = "base09"
"variable.other.member" = "base04"
"constant.character.escape" = "base0C"
"function" = "base0A"
"constructor" = "base0D"
"special" = "base0D"
"keyword" = "base0E"
"label" = "base08"
"namespace" = "base0E"
"punctuation" = "base08"
"ui.help" = { fg = "base06", bg = "base01" }

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }

[palette]
base00 = "#161616" # Default Background
base01 = "#262626" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#393939" # Selection Background
base03 = "#525252" # Comments, Invisibles, Line Highlighting
base04 = "#dde1e6" 
base05 = "#f2f4f8" # Default Foreground, Caret, Delimiters, Operators
base06 = "#ffffff" # Light Foreground (Not often used)
base07 = "#08bdba" # Light Background (Not often used)
base08 = "#3ddbd9" 
base09 = "#be95ff" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#ee5396" # Classes, Markup Bold, Search Text Background
base0B = "#33b1ff" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#ff7eb6" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#42be65" # Functions, Methods, Attribute IDs, Headings
base0E = "#78a9ff" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0F = "#82cfff" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
